User: Adrien
Measurements:
  # VS:
  #   instrument: SynkTek
  #   address: 172.22.11.2
  #   quantities: ["A-V1_L1_X", "A-V1_L1_Y", "A-V1_L1_R", "A-V1_L1_theta", "A-V1_L1_DC"]

  # Voltage:
  #   instrument: SR830
  #   quantity: ["R", "theta"]
  #   address: ASRL4::INSTR
  # T0:
  #   instrument: LS350
  #   quantity: ["Temperature_A"]
  #   timeout: 1000
  #   address: 192.168.0.12
  RR1:
    instrument: Random
    address: None
    quantities: ["Rand_1"]


# Saving info:
Saving:
  path: null
  file: file.dat

# Analysis info:
Analysis:
  Seebeck: False

