User: Adrien

# SR830 Lock-in Amplifier info:
Lockin:
  port: ASRL4::INSTR

# Lakeshore 350 Temperature Controller info:
LS350:
  timeout: 1000
  ip_address: '192.168.0.12'
  tcp_port: 7777

# Saving info:
Saving:
  filename: data.dat
  logname: data_log.dat
  folder: C:\Users\gourgout\Python\Resistivity\Data
  log_path: C:\Users\gourgout\Python\Resistivity\Data\data_log.dat
  data_path: C:\Users\gourgout\Python\Resistivity\Data\data.dat


# Measurement info:

Ramp:
  ramp_start_T: 5
  ramp_end_T: 100
  ramp_speed: 2 # in Kelvin/min

Step:
  