User: Adrien
Measurements:
  # VS:
  #   instrument: SynkTek
  #   address: 172.22.11.2
  #   channel: "A-V1_L1"
  #   quantities: ["X", "Y", "R", "theta", "DC"]
  # Voltage:
  #   instrument: SR830
  #   quantity: ["R", "theta"]
  #   address: ASRL4::INSTR
  # T0:
  #   instrument: LS350
  #   channel: "A"
  #   quantity: ["Temperature"]
  #   timeout: 1000
  #   address: 192.168.0.12
  RR1:
    instrument: RandomInt
    address: None
    channel: None
    quantities: ["Rand_1"]


# Saving info:
Saving:
  path: null
  file: file.dat

# Analysis info:
Analysis:
  Seebeck: False

