User: Adrien

# SR830 Lock-in Amplifier info:
Lockin:
  port: ASRL4::INSTR

# Lakeshore 350 Temperature Controller info:
LS350:
  timeout: 1000
  ip_address: '192.168.0.12'
  tcp_port: 7777

# Saving info:
Saving:
  filename: data.dat
  folder: C:\Users\gourgout\Python\Resistivity\V1\Data


# Measurement info:

Ramp:
  start_T:
  end_T:
  ramp_speed: