Analysis:
  Seebeck: false
Measurements:
  RR1:
    address: None
    channel: '1'
    instrument: Random
    quantities:
      Rand_1: true
  RR2:
    address: None
    channel: '2'
    instrument: Random
    quantities:
      Rand_2: true
  T+:
    address: 172.22.11.2
    channel: B-V1
    instrument: SynkTek
    quantities:
      DC: null
      R: null
      X: null
      Y: null
      theta: null
  T-:
    address: 172.22.11.2
    channel: B-V2
    instrument: SynkTek
    quantities:
      DC: null
      R: null
      X: null
      Y: null
      theta: null
  V_S:
    address: 172.22.11.2
    channel: A-V1
    instrument: SynkTek
    quantities:
      DC: null
      R: null
      X: null
      Y: null
      theta: null
Saving:
  file: file.dat
  path: null
User: Adrien
