User: Adrien
Measurements:
  VS:
    address: 172.22.11.2
    instrument: SynkTek
    quantities: ["A-V1_L1_X", "A-V1_L1_Y", "A-V1_L1_DC"]
  # XX:
  #   instrument: SR830
  #   quantity: X
  #   port: ASRL4::INSTR
  # YY:
  #   instrument: SR830
  #   quantity: Y
  #   address: ASRL4::INSTR
  # T0:
  #   instrument: LS350
  #   quantity: ["Temperature_A"]
  #   timeout: 1000
  #   address: '192.168.0.12'
  #   tcp_port: 7777
  # RR1:
  #   instrument: Random
  #   channel: Random_1
  #   address: None
  #   quantities:
  #     Rand1:
  # RR2:
  #   instrument: Random
  #   channel: Random_2
  #   address: None
  #   quantities:
  #     Rand1:
  T+:
    address: 172.22.11.2
    channel: B-V1
    instrument: SynkTek
    quantities:
      X:
      Y:
      R:
      theta:
      DC:
  T-:
    address: 172.22.11.2
    channel: B-V2
    instrument: SynkTek
    quantities:
      X:
      Y:
      R:
      theta:
      DC:



# Saving info:
Saving:
  path: null
  file: file.dat



# Analysis info:
Analysis:
  Seebeck: False

